# Generated by Django 4.2.13 on 2025-07-01 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('event_name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Первый день')),
                ('end_date', models.DateField(verbose_name='Последний день')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('annotation', models.CharField(max_length=1000, verbose_name='Аннотация')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('school', models.CharField(max_length=100, verbose_name='Место обучения')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('telegram', models.CharField(max_length=100, verbose_name='Телеграм')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('tag_name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('TAR', 'Аудитория'), ('FIE', 'Направление')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('timetable_name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(help_text='* в категорию входит время проведения мероприятия (11.00-12.00) или его время и тип (14.00-15.00, обед); для корректности отображения расписания важно вводить время в одном формате', max_length=100, verbose_name='Категория')),
                ('date', models.DateField(verbose_name='Дата')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('host', models.CharField(max_length=100, verbose_name='Ведущий')),
                ('annotation', models.CharField(max_length=1000, verbose_name='Аннотация')),
                ('repeating', models.BooleanField(default=False, editable=False, verbose_name='Повтор?')),
                ('seats_all', models.IntegerField(default=-1, verbose_name='Всего мест')),
                ('seats_taken', models.IntegerField(default=0, editable=False, verbose_name='Занято мест')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Элементы расписания',
            },
        ),
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.event', verbose_name='Событие')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег для события',
                'verbose_name_plural': 'Теги событий',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AFF', 'Еще не посещено'), ('INT', 'Пересекается'), ('WAI', 'Очередь'), ('VIS', 'Посещено'), ('MIS', 'Пропущено')], default='AFF', verbose_name='Статус')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.guest', verbose_name='Участник')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.timetable', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_name',), name='unique name'),
        ),
        migrations.AddConstraint(
            model_name='tagmap',
            constraint=models.UniqueConstraint(fields=('event', 'tag'), name='unique Tagmap'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('timetable', 'guest'), name='unique Registration'),
        ),
    ]
